defaults: &defaults

  # sites hosts
  # session expire seconds
  # admin role account
  URL_HOST: ${domain_url}
  URL_SCHEMA: http
  SESSION_EXPIRE: 60
  ADMIN: 'robert@arkivofficial.com'
  TIMEZONE: 'Cairo'

  REDIS_URL: redis://redis:6379

  # below settings only in production env
  # system notify mail settings
  # --------------------------------------------------------------
  SMTP_PORT: YOUR_SMTP_PORT
  SMTP_DOMAIN: YOUR_SMTP_DOMAIN
  SMTP_ADDRESS: YOUR_SMTP_ADDRESS
  SMTP_USERNAME: YOUR_SMTP_USERNAME
  SMTP_PASSWORD: YOUR_SMTP_PASSWORD
  SMTP_AUTHENTICATION: plain # could be plain, login or cram_md5

  SUPPORT_MAIL: help@arkivofficial.com
  SYSTEM_MAIL_FROM: help@arkivofficial.com
  SYSTEM_MAIL_TO: help@arkivofficial.com
  OPERATE_MAIL_TO: help@arkivofficial.com

  # WebSocket Streaming API settings
  # --------------------------------------------------------------
  WEBSOCKET_HOST: 0.0.0.0
  WEBSOCKET_PORT: 8080
  # Uncomment below to enable secure WebSocket (wss)
  #WEBSOCKET_SSL_KEY: 'your_server.key'
  #WEBSOCKET_SSL_CERT: 'your_server.crt'

  # pusher settings
  # --------------------------------------------------------------
  # peatio dependence Pusher (http://pusher.com) service
  # you can change your key for production environment.
  # we support development key and secret
  # uncomment below line only development or test
  #
  PUSHER_APP: theid
  PUSHER_KEY: 122312389
  PUSHER_SECRET: 75d6e6685209cc60cc4d
  PUSHER_HOST: pusher.arkivofficial.com
  PUSHER_PORT: 80
  PUSHER_WS_PORT: 80
  PUSHER_WSS_PORT: 443
  PUSHER_ENCRYPTED: true

  # twilio setting
  # --------------------------------------------------------------
  # https://github.com/twilio/twilio-ruby
  #
  TWILIO_NUMBER: +18476412290
  TWILIO_SID: AC017a29bd978dfb1da98a76a2049d7fed
  TWILIO_TOKEN: 57fa799d4e6f64bd5fc6bbcad22c4a40


  # Third party auth

  # Weibo
  # --------------------------------------------------------------
  WEIBO_AUTH: off # on/off
  WEIBO_KEY: 3820920586
  WEIBO_SECRET: 2d6174dc698e86860c75d75b1e8a01c8

  # chat setting
  # --------------------------------------------------------------
  # Do you want chat feature in your exchange ?
  # send mail to community@peatio.com

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
