- id: 1
  key: renminbi
  name: 'Coin name'
  code: cny
  symbol: "¥"
  coin: false
  precision: 2
  assets:
    accounts:
      -
        bank: '招商银行'
        address: '6225 0885 6022 3501'
        password: '111111'
        tel: '95555'
- id: 2
  key: satoshi
  name: 'Coin name'
  code: btc
  symbol: "฿"
  coin: true
  quick_withdraw_max: 0
  family: BTC
  rpc: ${rpc_url}
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: 1HjfnJpQmANtuW7yr1ggeDfyfe1kDK7rm3
- id: 4
  key: arkiv
  name: 'Air Bacon Warriors'
  code: abw
  symbol: "ABW"
  coin: true
  family: SHOE
- id: 5
  key: arkiv
  name: 'Air Force Max Fab 5'
  code: aff
  symbol: "AFF"
  coin: true
  family: SHOE
- id: 6
  key: arkiv
  name: 'Air Force 1 Low BHM'
  code: afl
  symbol: "AFL"
  coin: true
  family: SHOE
- id: 7
  key: arkiv
  name: 'Air Force 180 Olympics'
  code: afo
  symbol: "AFO"
  coin: true
  family: SHOE
- id: 8
  key: arkiv
  name: 'Air Force 1 07 Virgil X MOMA'
  code: afx
  symbol: "AFX"
  coin: true
  family: SHOE
- id: 9
  key: arkiv
  name: 'Air Max 95 Beaches or Rio'
  code: amb
  symbol: "AMB"
  coin: true
  family: SHOE
- id: 10
  key: arkiv
  name: 'Air Max Penny 1 Game Royal'
  code: amg
  symbol: "AMG"
  coin: true
  family: SHOE
- id: 11
  key: arkiv
  name: 'Air Max Penny 1 Orlando'
  code: amp
  symbol: "AMP"
  coin: true
  family: SHOE
- id: 12
  key: arkiv
  name: 'Air Max 90 Sunset Pack'
  code: ams
  symbol: "AMS"
  coin: true
  family: SHOE
- id: 13
  key: arkiv
  name: 'Air Presto Unholy Cumulus'
  code: apu
  symbol: "APU"
  coin: true
  family: SHOE
- id: 14
  key: arkiv
  name: 'Air Presto Off-White'
  code: apw
  symbol: "APW"
  coin: true
  family: SHOE
- id: 15
  key: arkiv
  name: 'Air Vapormax Off-White Black'
  code: avb
  symbol: "AVB"
  coin: true
  family: SHOE
- id: 16
  key: arkiv
  name: 'Blazer Geoff McFetridge'
  code: bgm
  symbol: "BGM"
  coin: true
  family: SHOE
- id: 17
  key: arkiv
  name: 'Foamposite Dr. Doom'
  code: fdd
  symbol: "FDD"
  coin: true
  family: SHOE
- id: 18
  key: arkiv
  name: 'Jordan 13 Altitude'
  code: jal
  symbol: "JAL"
  coin: true
  family: SHOE
- id: 19
  key: arkiv
  name: 'Jordan 4 30th Anniversary Laser'
  code: jan 
  symbol: "JAN"
  coin: true
  family: SHOE
- id: 20
  key: arkiv
  name: 'Jordan 8 Aqua'
  code: jaq
  symbol: "JAN"
  coin: true
  family: SHOE
- id: 21
  key: arkiv
  name: 'Jordan 8 Bugs Bunny'
  code: jbb
  symbol: "JBB"
  coin: true
  family: SHOE
- id: 22
  key: arkiv
  name: 'Jordan 15 Bred CDP'
  code: jbc
  symbol: "JBC"
  coin: true
  family: SHOE
- id: 23
  key: arkiv
  name: ' Jordan 5 Black Grape'
  code: jbg
  symbol: "JBG"
  coin: true
  family: SHOE
- id: 24
  key: arkiv
  name: 'Jordan 13 Bred'
  code: jbr
  symbol: "JBR"
  coin: true
  family: SHOE
- id: 25
  key: arkiv
  name: 'Jordan 5 Black/University Blue'
  code: jbu
  symbol: "JBU"
  coin: true
  family: SHOE  
- id: 26
  key: arkiv
  name: 'Jordan 9 Calvin Bailey'
  code: jcb
  symbol: "JCB"
  coin: true
  family: SHOE  
- id: 27
  key: arkiv
  name: 'Jordan 14 Candy Cane'
  code: jcc
  symbol: "JCC"
  coin: true
  family: SHOE
- id: 28
  key: arkiv
  name: 'Jordan 8 Chrome'
  code: jch
  symbol: "JCH"
  coin: true
  family: SHOE  
- id: 29
  key: arkiv
  name: 'Jordan 17 Copper'
  code: jco
  symbol: "JCO"
  coin: true
  family: SHOE  
- id: 30
  key: arkiv
  name: 'Jordan 13 Cherry'
  code: jcr
  symbol: "JCR"
  coin: true
  family: SHOE 
- id: 31
  key: arkiv
  name: 'Jordan 7 DMP Magic'
  code: jdm
  symbol: "JDM"
  coin: true
  family: SHOE
- id: 32
  key: arkiv
  name: 'Jordan 3 Fire Red'
  code: jfe
  symbol: "JFE"
  coin: true
  family: SHOE
- id: 33
  key: arkiv
  name: 'Jordan 12 Flu Game'
  code: jfg
  symbol: "JFG"
  coin: true
  family: SHOE
- id: 34
  key: arkiv
  name: 'Jordan 4 Fire Red'
  code: jfi
  symbol: "JFI"
  coin: true
  family: SHOE
- id: 35
  key: arkiv
  name: 'Jordan 9 Fontay Montana Knicks'
  code: jfm
  symbol: "JFM"
  coin: true
  family: SHOE
- id: 36
  key: arkiv
  name: 'Jordan 3 Fear Pack'
  code: jfp
  symbol: "JFP"
  coin: true
  family: SHOE
- id: 37
  key: arkiv
  name: 'Jordan Future QS Glow'
  code: jgq
  symbol: "JGQ"
  coin: true
  family: SHOE
- id: 38
  key: arkiv
  name: 'Jordan 5 Fire Red'
  code: jfr
  symbol: "JFR"
  coin: true
  family: SHOE
- id: 39
  key: arkiv
  name: 'Jordan 5 Green Bean'
  code: jgb 
  symbol: "JGB"
  coin: true
  family: SHOE
- id: 40
  key: arkiv
  name: 'Jordan 6 Golden Moments'
  code: jgm
  symbol: "JGM"
  coin: true
  family: SHOE
- id: 41
  key: arkiv
  name: 'Jordan 21 Graphite'
  code: jgp
  symbol: "JGP"
  coin: true
  family: SHOE
- id: 42
  key: arkiv
  name: 'Jordan 5 Grape'
  code: jgr
  symbol: "JGR"
  coin: true
  family: SHOE
- id: 43
  key: arkiv
  name: 'Jordan 1 Retro High NRG Patent Gold Toe'
  code: jhp
  symbol: "JHP"
  coin: true
  family: SHOE
- id: 44
  key: arkiv
  name: 'Jordan 6 Infrared Black'
  code: jib
  symbol: "JIB"
  coin: true
  family: SHOE
- id: 45
  key: arkiv
  name: 'Jordan 7 J2K Filbert'
  code: jjf
  symbol: "JJF"
  coin: true
  family: SHOE
- id: 46
  key: arkiv
  name: 'Jordan 3 Retro JTH Superbowl'
  code: jjs
  symbol: "JJS"
  coin: true
  family: SHOE
- id: 47
  key: arkiv
  name: 'Jordan 5 Laney'
  code: jla
  symbol: "JLA"
  coin: true
  family: SHOE
- id: 48
  key: arkiv
  name: 'Jordan 14 Laney'
  code: jly
  symbol: "JLY"
  coin: true
  family: SHOE
- id: 49
  key: arkiv
  name: 'Jordan 9 Motorboat Jones'
  code: jmj
  symbol: "JMJ"
  coin: true
  family: SHOE
- id: 50
  key: arkiv
  name: 'Jordan 13 Neutral Grey'
  code: jng
  symbol: "JNG"
  coin: true
  family: SHOE
- id: 51
  key: arkiv
  name: 'Jordan 20 OG Quickstrike'
  code: jog
  symbol: "JOG"
  coin: true
  family: SHOE
- id: 52
  key: arkiv
  name: 'Jordan 6 Olympic London'
  code: jol
  symbol: "JOL"
  coin: true
  family: SHOE
- id: 53
  key: arkiv
  name: 'Jordan 9 Photo Blue'
  code: jpb
  symbol: "JPB"
  coin: true
  family: SHOE
- id: 54
  key: arkiv
  name: 'Jordan 12 Playoffs'
  code: jpl
  symbol: "JPL"
  coin: true
  family: SHOE
- id: 55
  key: arkiv
  name: 'Jordan 9 Powder'
  code: jpo
  symbol: "JPO"
  coin: true
  family: SHOE