- id: 1
  key: renminbi
  name: 'Coin name'
  code: cny
  symbol: "¥"
  coin: false
  precision: 2
  assets:
    accounts:
      -
        bank: '招商银行'
        address: '6225 0885 6022 3501'
        password: '111111'
        tel: '95555'
- id: 2
  key: satoshi
  name: 'Coin name'
  code: btc
  symbol: "฿"
  coin: true
  quick_withdraw_max: 0
  family: BTC
  rpc: ${rpc_url}
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: 1HjfnJpQmANtuW7yr1ggeDfyfe1kDK7rm3
- id: 4
  key: arkiv
  name: 'Air Bacon Warriors'
  code: abw
  symbol: "ABW"
  coin: true
  family: SHOE
- id: 5
  key: arkiv
  name: 'Air Force Max Fab 5'
  code: aff
  symbol: "AFF"
  coin: true
  family: SHOE
- id: 6
  key: arkiv
  name: 'Air Force 1 Low BHM'
  code: afl
  symbol: "AFL"
  coin: true
  family: SHOE
- id: 7
  key: arkiv
  name: 'Air Force 180 Olympics'
  code: afo
  symbol: "AFO"
  coin: true
  family: SHOE