development: &defaults
  adapter: mysql2
  encoding: utf8
  database: peatio_development
  username: root
  password:
  pool: 10
  reconnect: true
  
production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV["MYSQL_DATABASE"] %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  pool: 10
  reconnect: true
  host: <%= ENV["MYSQL_HOST"] %>
