development: &defaults
  adapter: mysql2
  encoding: utf8
  database: peatio_development
  username: root
  password: 
  pool: 10
  reconnect: true
  
production:
  adapter: mysql2
  encoding: utf8
  database: arkivrobert
  username: ArkivRobert
  password: 6c1df874c4a895f73d62
  pool: 10
  reconnect: true
  host: arkivrobert.cg9fktyrkxhs.us-east-2.rds.amazonaws.com
