development: &defaults
  adapter: mysql2
  encoding: utf8
  database: peatio_development
  username: peatio
  password: peatio
  pool: 10
  reconnect: true
  host: mysql

test:
  <<: *defaults
  database: peatio_test

production:
  <<: *defaults
  database: peatio
