- id: 200
  key: satoshi
  currency: btc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 400
  key: bank
  currency: cny
  sort_order: 2
  bank_accounts:
    -
      bank: 'Your Bank Name'
      branch: 'Your Bank Branch'
      holder: 'Your Account Holder'
      account: 'Your Account Number'
- id: 1000
  key: arkiv
  currency: abw
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1001
  key: arkiv
  currency: aff
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1002
  key: arkiv
  currency: afl
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1003
  key: arkiv
  currency: afo
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1004
  key: arkiv
  currency: afx
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1005
  key: arkiv
  currency: amb
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1006
  key: arkiv
  currency: amg
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1007
  key: arkiv
  currency: amp
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1008
  key: arkiv
  currency: ams
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1009
  key: arkiv
  currency: apu
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1010
  key: arkiv
  currency: apw
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1011
  key: arkiv
  currency: avb
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1012
  key: arkiv
  currency: bgm
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1013
  key: arkiv
  currency: fdd
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1014
  key: arkiv
  currency: jal
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1015
  key: arkiv
  currency: jan
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1016
  key: arkiv
  currency: jaq
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1017
  key: arkiv
  currency: jbb
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1018
  key: arkiv
  currency: jbc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1019
  key: arkiv
  currency: jbg
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1020
  key: arkiv
  currency: jbr
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1021
  key: arkiv
  currency: jbu
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1022
  key: arkiv
  currency: jcb
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1023
  key: arkiv
  currency: jcc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3