- id: satoshi
  code: 200
  currency: btc
  link: /deposits/coin?currency=btc
  description: btc
  confirm: 1
  confirm_max: 6
  low: 0.1
  transfer: now
  latency: 10
- id: bank
  code: 400
  currency: cny
  link: /deposits/bank
  description: cny
  transfer: now
  latency: 10
  account_bank: Fack Bank Name
  account_holder: Fack Card Holder
  account_number: Fack Card Number

