- id: 200
  key: satoshi
  currency: btc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 400
  key: bank
  currency: btc
  sort_order: 2
  bank_accounts:
    -
      bank: 'Your Bank Name'
      branch: 'Your Bank Branch'
      holder: 'Your Account Holder'
      account: 'Your Account Number'
- id: 1000
  key: satoshi
  currency: abw
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1001
  key: satoshi
  currency: aff
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1002
  key: satoshi
  currency: afl
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1003
  key: satoshi
  currency: afo
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1004
  key: satoshi
  currency: afx
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1005
  key: satoshi
  currency: amb
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1006
  key: satoshi
  currency: amg
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1007
  key: satoshi
  currency: amp
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1008
  key: satoshi
  currency: ams
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1009
  key: satoshi
  currency: apu
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1010
  key: satoshi
  currency: apw
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1011
  key: satoshi
  currency: avb
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1012
  key: satoshi
  currency: bgm
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1013
  key: satoshi
  currency: fdd
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1014
  key: satoshi
  currency: jal
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1015
  key: satoshi
  currency: jan
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1016
  key: satoshi
  currency: jaq
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1017
  key: satoshi
  currency: jbb
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1018
  key: satoshi
  currency: jbc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1019
  key: satoshi
  currency: jbg
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1020
  key: satoshi
  currency: jbr
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1021
  key: satoshi
  currency: jbu
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1022
  key: satoshi
  currency: jcb
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1023
  key: satoshi
  currency: jcc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1024
  key: satoshi
  currency: jch
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1025
  key: satoshi
  currency: jco
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1026
  key: satoshi
  currency: jcr
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1027
  key: satoshi
  currency: jdm
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1028
  key: satoshi
  currency: jfe
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1029
  key: satoshi
  currency: jf6
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1030
  key: satoshi
  currency: jfi
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1031
  key: satoshi
  currency: jfm
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1032
  key: satoshi
  currency: jfp
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1033
  key: satoshi
  currency: jgq
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1034
  key: satoshi
  currency: jfr
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1035
  key: satoshi
  currency: jgb
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1036
  key: satoshi
  currency: jgm
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1037
  key: satoshi
  currency: jgp
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1038
  key: satoshi
  currency: jgr
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1039
  key: satoshi
  currency: jhp
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1040
  key: satoshi
  currency: jib
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1041
  key: satoshi
  currency: jjf
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1042
  key: satoshi
  currency: jjs
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1043
  key: satoshi
  currency: jla
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1044
  key: satoshi
  currency: jly
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1045
  key: satoshi
  currency: jmj
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1046
  key: satoshi
  currency: jng
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1047
  key: satoshi
  currency: jog
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1048
  key: satoshi
  currency: jol
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1049
  key: satoshi
  currency: jpb
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1050
  key: satoshi
  currency: jpl
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 1051
  key: satoshi
  currency: jpo
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 56 
  key: satoshi
  currency: jps 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 57
  key: satoshi
  currency: jra
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 58 
  key: satoshi
  currency: jrb
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 59
  key: satoshi
  currency: jrc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 60
  key: satoshi
  currency: jrh
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 61
  key: satoshi
  currency: jro
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 62 
  key: satoshi
  currency: jrr 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 63 
  key: satoshi
  currency: jrt 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 64 
  key: satoshi
  currency: jry
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 65 
  key: satoshi
  currency: jsa 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 66
  key: satoshi
  currency: jse 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 67
  key: satoshi
  currency: jsj 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 68
  key: satoshi
  currency: jsl
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 69
  key: satoshi
  currency: jsr 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 70 
  key: satoshi
  currency: jst 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 71
  key: satoshi
  currency: jtb
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 72
  key: satoshi
  currency: jth 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 73
  key: satoshi
  currency: jty 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 74
  key: satoshi
  currency: jwc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 75
  key: satoshi
  currency: kap 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 76
  key: satoshi
  currency: kbh 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 77
  key: satoshi
  currency: kde
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 78
  key: satoshi
  currency: kea 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 79
  key: satoshi
  currency: keb 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 80
  key: satoshi
  currency: kee
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 81
  key: satoshi
  currency: kel 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 82
  key: satoshi
  currency: kef
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 83
  key: satoshi
  currency: kgf 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 84
  key: satoshi
  currency: kin 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 85
  key: satoshi
  currency: kng 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 86
  key: satoshi
  currency: krg
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 87
  key: satoshi
  currency: kse
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 88
  key: satoshi
  currency: ksp
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 89
  key: satoshi
  currency: kst 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 90
  key: satoshi
  currency: kvb 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 91
  key: satoshi
  currency: laa
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 92
  key: satoshi
  currency: lbb
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 93
  key: satoshi
  currency: lbhx 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 94
  key: satoshi
  currency: lbh
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 95
  key: satoshi
  currency: lbs
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 96
  key: satoshi
  currency: lcg
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 97
  key: satoshi
  currency: lch
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 98
  key: satoshi
  currency: led 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 99
  key: satoshi
  currency: leh 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 100
  key: satoshi
  currency: les 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 101
  key: satoshi
  currency: lfc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 102
  key: satoshi
  currency: lfg 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 103
  key: satoshi
  currency: lfi
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 104
  key: satoshi
  currency: lma 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 105
  key: satoshi
  currency: lmh 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 106
  key: satoshi
  currency: lmhh
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 107
  key: satoshi
  currency: lmhb
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 108
  key: satoshi
  currency: lsl 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 109
  key: satoshi
  currency: lxc 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 110
  key: satoshi
  currency: mud
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 111
  key: satoshi
  currency: muo 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 112
  key: satoshi
  currency: nap 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 113
  key: satoshi
  currency: ndc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 114
  key: satoshi
  currency: ndh 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 115
  key: satoshi
  currency: ndg 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 116
  key: satoshi
  currency: ndl 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 117
  key: satoshi
  currency: rrg 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 118
  key: satoshi
  currency: ybb 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 119
  key: satoshi
  currency: ybc 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 120
  key: satoshi
  currency: ybt 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 121
  key: satoshi
  currency: ybz 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 122
  key: satoshi
  currency: zrg 
  sort_order: 1
  min_confirm: 1
  max_confirm: 3