- id: 200
  key: satoshi
  currency: btc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 400
  key: bank
  currency: cny
  fixed: 2
  fee_max: 0
  min: 100
  max: 50000
  fee: 0.003
  proportion: true
  inuse: true
  type: WithdrawChannelBank
- id: 500
  key: ether
  currency: eth
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0005
  type: WithdrawChannelEthereum
- id: 1000
  key: arkiv
  currency: abw
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1001
  key: arkiv
  currency: aff
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1002
  key: arkiv
  currency: afl
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1003
  key: arkiv
  currency: afo
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1004
  key: arkiv
  currency: afx
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1005
  key: arkiv
  currency: amb
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1006
  key: arkiv
  currency: amg
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1007
  key: arkiv
  currency: amp
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1008
  key: arkiv
  currency: ams
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1009
  key: arkiv
  currency: apu
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1010
  key: arkiv
  currency: apw
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1011
  key: arkiv
  currency: avb
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi 
- id: 1012
  key: arkiv
  currency: bgm
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi 
- id: 1013
  key: arkiv
  currency: fdd
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1014
  key: arkiv
  currency: jal
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1015
  key: arkiv
  currency: jan
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1016
  key: arkiv
  currency: jaq
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1017
  key: arkiv
  currency: jbb
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi 
- id: 1018
  key: arkiv
  currency: jbc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1019
  key: arkiv
  currency: jbg
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1020
  key: arkiv
  currency: jbr
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1021
  key: arkiv
  currency: jbu
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1022
  key: arkiv
  currency: jcb
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1023
  key: arkiv
  currency: jcc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1024
  key: arkiv
  currency: jch
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1025
  key: arkiv
  currency: jco
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1026
  key: arkiv
  currency: jcr
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1027
  key: arkiv
  currency: jdm
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1028
  key: arkiv
  currency: jfe
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1029
  key: arkiv
  currency: jfg
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1030
  key: arkiv
  currency: jfi
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1031
  key: arkiv
  currency: jfm
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1032
  key: arkiv
  currency: jfp
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1033
  key: arkiv
  currency: jgq
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1034
  key: arkiv
  currency: jfr
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1035
  key: arkiv
  currency: jgb
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1036
  key: arkiv
  currency: jgm
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1037
  key: arkiv
  currency: jgp
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1038
  key: arkiv
  currency: jgr
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  