- id: satoshi
  code: 200
  currency: btc
  fixed: 8
  fee: 0.0005
  inuse: true
- id: bank
  code: 400
  currency: cny
  fixed: 2
  fee_max: 0
  low: 100
  max: 50000
  fee: 0.005
  proportion: true
  inuse: true
