- id: 200
  key: satoshi
  currency: btc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 400
  key: bank
  currency: cny
  fixed: 2
  fee_max: 0
  min: 100
  max: 50000
  fee: 0.003
  proportion: true
  inuse: true
  type: WithdrawChannelBank
- id: 500
  key: ether
  currency: eth
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0005
  type: WithdrawChannelEthereum
- id: 1000
  key: arkiv
  currency: abw
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1001
  key: arkiv
  currency: aff
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1002
  key: arkiv
  currency: afl
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1003
  key: arkiv
  currency: afo
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1004
  key: arkiv
  currency: afx
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1005
  key: arkiv
  currency: amb
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1006
  key: arkiv
  currency: amg
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1007
  key: arkiv
  currency: amp
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1008
  key: arkiv
  currency: ams
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1009
  key: arkiv
  currency: apu
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1010
  key: arkiv
  currency: apw
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1011
  key: arkiv
  currency: avb
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi 
- id: 1012
  key: arkiv
  currency: bgm
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi 
- id: 1013
  key: arkiv
  currency: fdd
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1014
  key: arkiv
  currency: jal
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1015
  key: arkiv
  currency: jan
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1016
  key: arkiv
  currency: jaq
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1017
  key: arkiv
  currency: jbb
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi 
- id: 1018
  key: arkiv
  currency: jbc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1019
  key: arkiv
  currency: jbg
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1020
  key: arkiv
  currency: jbr
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1021
  key: arkiv
  currency: jbu
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1022
  key: arkiv
  currency: jcb
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1023
  key: arkiv
  currency: jcc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1024
  key: arkiv
  currency: jch
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1025
  key: arkiv
  currency: jco
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1026
  key: arkiv
  currency: jcr
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1027
  key: arkiv
  currency: jdm
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1028
  key: arkiv
  currency: jfe
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1029
  key: arkiv
  currency: jfg
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1030
  key: arkiv
  currency: jfi
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1031
  key: arkiv
  currency: jfm
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1032
  key: arkiv
  currency: jfp
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1033
  key: arkiv
  currency: jgq
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1034
  key: arkiv
  currency: jfr
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1035
  key: arkiv
  currency: jgb
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1036
  key: arkiv
  currency: jgm
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1037
  key: arkiv
  currency: jgp
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1038
  key: arkiv
  currency: jgr
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1039
  key: arkiv
  currency: jhp
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1040
  key: arkiv
  currency: jib
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1041
  key: arkiv
  currency: jjf
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1042
  key: arkiv
  currency: jjs
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1043
  key: arkiv
  currency: jla
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1044
  key: arkiv
  currency: jly
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1045
  key: arkiv
  currency: jmj
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1046
  key: arkiv
  currency: jng
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1047
  key: arkiv
  currency: jog
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1048
  key: arkiv
  currency: jol
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1049
  key: arkiv
  currency: jpb
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1050
  key: arkiv
  currency: jpl
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  
- id: 1051
  key: arkiv
  currency: jpo
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1052 
  key: arkiv
  currency: jps 
  fixed: 1053
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1054
  key: arkiv
  currency: jra
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 1056
  key: arkiv
  currency: jrb
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 59
  key: arkiv
  currency: jrc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 60
  key: arkiv
  currency: jrh
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 61
  key: arkiv
  currency: jro
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 62 
  key: arkiv
  currency: jrr 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 63 
  key: arkiv
  currency: jrt 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 64 
  key: arkiv
  currency: jry
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 65 
  key: arkiv
  currency: jsa 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 66
  key: arkiv
  currency: jse 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 67
  key: arkiv
  currency: jsj 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 68
  key: arkiv
  currency: jsl
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 69
  key: arkiv
  currency: jsr 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 70 
  key: arkiv
  currency: jst 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 71
  key: arkiv
  currency: jtb
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 72
  key: arkiv
  currency: jth 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 73
  key: arkiv
  currency: jty 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 74
  key: arkiv
  currency: jwc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 75
  key: arkiv
  currency: kap 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 76
  key: arkiv
  currency: kbh 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 77
  key: arkiv
  currency: kde
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 78
  key: arkiv
  currency: kea 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 79
  key: arkiv
  currency: keb 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 80
  key: arkiv
  currency: kee
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 81
  key: arkiv
  currency: kel 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 82
  key: arkiv
  currency: kef
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 83
  key: arkiv
  currency: kgf 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 84
  key: arkiv
  currency: kin 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 85
  key: arkiv
  currency: kng 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 86
  key: arkiv
  currency: krg
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 87
  key: arkiv
  currency: kse
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 88
  key: arkiv
  currency: ksp
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 89
  key: arkiv
  currency: kst 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 90
  key: arkiv
  currency: kvb 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 91
  key: arkiv
  currency: laa
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 92
  key: arkiv
  currency: lbb
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 93
  key: arkiv
  currency: lbhx 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 94
  key: arkiv
  currency: lbh
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 95
  key: arkiv
  currency: lbs
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 96
  key: arkiv
  currency: lcg
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 97
  key: arkiv
  currency: lch
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 98
  key: arkiv
  currency: led 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 99
  key: arkiv
  currency: leh 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 100
  key: arkiv
  currency: les 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 101
  key: arkiv
  currency: lfc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 102
  key: arkiv
  currency: lfg 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 103
  key: arkiv
  currency: lfi
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 104
  key: arkiv
  currency: lma 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 105
  key: arkiv
  currency: lmh 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 106
  key: arkiv
  currency: lmhh
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 107
  key: arkiv
  currency: lmhb
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 108
  key: arkiv
  currency: lsl 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 109
  key: arkiv
  currency: lxc 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 110
  key: arkiv
  currency: mud
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 111
  key: arkiv
  currency: muo 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 112
  key: arkiv
  currency: nap 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 113
  key: arkiv
  currency: ndc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 114
  key: arkiv
  currency: ndh 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 115
  key: arkiv
  currency: ndg 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 116
  key: arkiv
  currency: ndl 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 117
  key: arkiv
  currency: rrg 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 118
  key: arkiv
  currency: ybb 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 119
  key: arkiv
  currency: ybc 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 120
  key: arkiv
  currency: ybt 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 121
  key: arkiv
  currency: ybz 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 122
  key: arkiv
  currency: zrg 
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi  